#Origen del directorio donde se encuentra el repositorio local u origen de los File.
origin: 
      repositoryDir:  C:\Users\JAVIER\Desktop\
      cssDir:
      jsDir:
      htmlDir:
      imgDir:
      docDir:

#Espacio de trabajo donde se va a trabajar, si no existiera el directorio se crea.
workspaces:
        -  path: C:\Users\JAVIER\Desktop\dir-loc
           localeRefs:
            - es_ES
            - en_US
            - eu_ES   
        - path: C:\Users\JAVIER\Desktop\dir-loc2
          localeRefs:
            - es_ES
            - en_US
            - eu_ES 