---
workspaces:
- "C://SampleDir"
- "C://OtherSampleWorkspace"
origin:
  repositoryDir: "C://RepoDirSample"
  cssDir: "/cssDirSample"
  jsDir: "/jsDirSample"
  htmlDir: "/htmlDirSample"
  imgDir: "/imgDirSample"
  docDir: "/docDirSample"
commandsSessionStorage: 10
age: 3600
theme:
  bgColor:
    hex: null
    r: 10
    g: 10
    b: 10
    a: 0.5
  fgColor:
    hex: "#212F3D"
    r: 0
    g: 0
    b: 0
    a: 0.0
