theme: FlatGitHubDarkIJTheme
#Índice de origen y workspace activos, actualizable tanto por GUI como por YML+GUI
workspace: 0
origin: 0

#Origen del directorio donde se encuentra el repositorio local u origen de los File.
origins: 
     -  repositoryDir:  C:\Users\JAVIER\Desktop\
        cssDir:
        jsDir:
        htmlDir:
        imgDir:
        docDir:
     -  repositoryDir:  C:\Users\JAVIER\Desktop\loqsea
        cssDir:
        jsDir:
        htmlDir:
        imgDir:
        docDir:

#Espacio de trabajo donde se va a trabajar, si no existiera el directorio se crea.
workspaces:
        -  dirPath: C:\Users\JAVIER\Desktop\dir-loc
           localeRefs:
            - es_ES
            - en_US
            - eu_ES   
        - dirPath: C:\Users\JAVIER\Desktop\dir-loc2
          localeRefs:
            - es_ES
            - en_US
            - eu_ES 